version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"  
    environment:
      - KAFKA_BROKER=kafka:9092 
    depends_on:
      - kafka

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    volumes:
      - kafka_data:/bitnami

volumes:
  kafka_data: