# # Базовый образ (без уязвимостей)
# FROM python:3.13-slim-bookworm

# # Рабочая директория
# WORKDIR /app

# # Копируем зависимости и устанавливаем их
# COPY requirements.txt .
# RUN pip install --no-cache-dir -r requirements.txt

# # Копируем весь код
# COPY . .

# # Запускаем сервис на порту 8002
# CMD ["python", "run.py"]